//
//  This file is part of the 2FAS Browser Extension (https://github.com/twofas/2fas-browser-extension)
//  Copyright © 2026 Two Factor Authentication Service, Inc.
//  Contributed by Grzegorz Zając. All rights reserved.
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program. If not, see <https://www.gnu.org/licenses/>
//

/**
 * Array of multilingual button text strings for identifying submit/verify buttons.
 * @type {string[]}
 */
const buttonsTexts = [
  // English
  'verify',
  'verify code',
  'confirm',
  'confirm code',
  'submit',
  'submit code',
  'send',
  'send code',
  'validate',
  'validate code',
  'authenticate',
  'continue',
  'proceed',
  'next',
  'next step',
  'done',
  'complete',
  'finish',
  'ok',
  'go',

  // Polish
  'zweryfikuj',
  'zweryfikuj kod',
  'weryfikuj',
  'weryfikuj kod',
  'potwierdź',
  'potwierdź kod',
  'wyślij',
  'wyślij kod',
  'zatwierdź',
  'kontynuuj',
  'dalej',
  'następny',
  'następny krok',
  'gotowe',
  'zakończ',

  // German
  'bestätigen',
  'bestätige',
  'code bestätigen',
  'verifizieren',
  'code verifizieren',
  'überprüfen',
  'code überprüfen',
  'senden',
  'code senden',
  'absenden',
  'weiter',
  'fortfahren',
  'nächster',
  'nächster schritt',
  'fertig',

  // French
  'vérifier',
  'vérifier le code',
  'confirmer',
  'confirmer le code',
  'envoyer',
  'envoyer le code',
  'valider',
  'valider le code',
  'soumettre',
  'continuer',
  'suivant',
  'prochaine étape',
  'terminer',
  'terminé',

  // Spanish
  'verificar',
  'verificar código',
  'confirmar',
  'confirmar código',
  'enviar',
  'enviar código',
  'validar',
  'validar código',
  'continuar',
  'siguiente',
  'siguiente paso',
  'listo',
  'finalizar',
  'hecho',

  // Portuguese
  'verificar',
  'verificar código',
  'confirmar',
  'confirmar código',
  'enviar',
  'enviar código',
  'validar',
  'validar código',
  'continuar',
  'próximo',
  'próximo passo',
  'concluir',
  'concluído',
  'pronto',

  // Italian
  'verifica',
  'verifica codice',
  'conferma',
  'conferma codice',
  'invia',
  'invia codice',
  'convalida',
  'convalida codice',
  'continua',
  'avanti',
  'prossimo',
  'prossimo passo',
  'fatto',
  'fine',
  'completa',

  // Dutch
  'verifiëren',
  'verifieer',
  'code verifiëren',
  'bevestigen',
  'bevestig',
  'code bevestigen',
  'versturen',
  'verzenden',
  'code verzenden',
  'valideren',
  'doorgaan',
  'volgende',
  'volgende stap',
  'klaar',
  'gereed',

  // Turkish
  'doğrula',
  'doğrula kodu',
  'kodu doğrula',
  'onayla',
  'onaylayın',
  'kodu onayla',
  'gönder',
  'kodu gönder',
  'devam',
  'devam et',
  'sonraki',
  'sonraki adım',
  'tamam',
  'bitti',
  'tamamla',

  // Indonesian
  'verifikasi',
  'verifikasi kode',
  'konfirmasi',
  'konfirmasi kode',
  'kirim',
  'kirim kode',
  'validasi',
  'lanjutkan',
  'berikutnya',
  'langkah selanjutnya',
  'selesai',

  // Greek
  'επιβεβαίωση',
  'επιβεβαίωση κωδικού',
  'επαλήθευση',
  'επαλήθευση κωδικού',
  'αποστολή',
  'αποστολή κωδικού',
  'συνέχεια',
  'επόμενο',
  'επόμενος',
  'επόμενο βήμα',
  'ολοκλήρωση',
  'έτοιμο',

  // Japanese
  '確認',
  '確認する',
  'コードを確認',
  '認証',
  '認証する',
  'コードを認証',
  '送信',
  '送信する',
  'コードを送信',
  '検証',
  '検証する',
  '次へ',
  '続ける',
  '完了',

  // Korean
  '확인',
  '코드 확인',
  '인증',
  '코드 인증',
  '전송',
  '코드 전송',
  '제출',
  '검증',
  '계속',
  '다음',
  '다음 단계',
  '완료',

  // Chinese (Simplified)
  '验证',
  '验证码',
  '验证代码',
  '确认',
  '确认代码',
  '发送',
  '发送代码',
  '提交',
  '提交代码',
  '继续',
  '下一步',
  '完成',

  // Chinese (Traditional)
  '驗證',
  '驗證碼',
  '驗證代碼',
  '確認',
  '確認代碼',
  '發送',
  '發送代碼',
  '提交',
  '提交代碼',
  '繼續',
  '下一步',
  '完成',

  // Arabic
  'تحقق',
  'تأكيد',
  'تأكيد الرمز',
  'إرسال',
  'إرسال الرمز',
  'التالي',
  'الخطوة التالية',
  'متابعة',
  'تم',
  'إنهاء',

  // Hebrew
  'אמת',
  'אימות',
  'אשר',
  'אישור',
  'אשר קוד',
  'שלח',
  'שלח קוד',
  'המשך',
  'הבא',
  'סיום',

  // Hindi
  'सत्यापित करें',
  'कोड सत्यापित करें',
  'पुष्टि करें',
  'कोड पुष्टि करें',
  'भेजें',
  'कोड भेजें',
  'जारी रखें',
  'अगला',
  'अगला कदम',
  'हो गया',
  'पूर्ण',

  // Thai
  'ยืนยัน',
  'ยืนยันรหัส',
  'ตรวจสอบ',
  'ตรวจสอบรหัส',
  'ส่ง',
  'ส่งรหัส',
  'ดำเนินการต่อ',
  'ถัดไป',
  'ขั้นตอนถัดไป',
  'เสร็จสิ้น',

  // Vietnamese
  'xác minh',
  'xác minh mã',
  'xác nhận',
  'xác nhận mã',
  'gửi',
  'gửi mã',
  'tiếp tục',
  'tiếp theo',
  'bước tiếp theo',
  'hoàn tất',
  'xong',

  // Czech
  'ověřit',
  'ověřit kód',
  'potvrdit',
  'potvrdit kód',
  'odeslat',
  'odeslat kód',
  'pokračovat',
  'další',
  'další krok',
  'hotovo',
  'dokončit',

  // Swedish
  'verifiera',
  'verifiera kod',
  'bekräfta',
  'bekräfta kod',
  'skicka',
  'skicka kod',
  'fortsätt',
  'nästa',
  'nästa steg',
  'klar',
  'slutför',

  // Norwegian
  'bekreft',
  'bekreft kode',
  'verifiser',
  'verifiser kode',
  'send',
  'send kode',
  'fortsett',
  'neste',
  'neste steg',
  'ferdig',
  'fullfør',

  // Danish
  'bekræft',
  'bekræft kode',
  'verificer',
  'verificer kode',
  'send',
  'send kode',
  'fortsæt',
  'næste',
  'næste trin',
  'færdig',

  // Finnish
  'vahvista',
  'vahvista koodi',
  'varmista',
  'varmista koodi',
  'lähetä',
  'lähetä koodi',
  'jatka',
  'seuraava',
  'seuraava vaihe',
  'valmis',

  // Hungarian
  'megerősítés',
  'megerősít',
  'kód megerősítése',
  'ellenőrzés',
  'ellenőriz',
  'kód ellenőrzése',
  'küldés',
  'küld',
  'kód küldése',
  'tovább',
  'következő',
  'következő lépés',
  'kész',
  'befejezés',

  // Romanian
  'verifică',
  'verificare',
  'verifică codul',
  'confirmă',
  'confirmare',
  'confirmă codul',
  'trimite',
  'trimite codul',
  'continuă',
  'următorul',
  'pasul următor',
  'gata',
  'finalizare'
];

export default buttonsTexts;
