//
//  This file is part of the 2FAS Browser Extension (https://github.com/twofas/2fas-browser-extension)
//  Copyright © 2026 Two Factor Authentication Service, Inc.
//  Contributed by Grzegorz Zając. All rights reserved.
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program. If not, see <https://www.gnu.org/licenses/>
//

const ignoreButtonTexts = () => {
  return [
    // English
    'search',
    'close',
    'cancel',
    'back',
    'go back',
    'previous',
    'join',
    'register',
    'sign up',
    'create account',
    'reset',
    'resend',
    'resend code',
    'send again',
    'try again',
    'help',
    'skip',
    'later',
    'remind me later',
    'not now',
    'use another method',
    'try another way',
    'change method',
    'forgot password',
    'reset password',
    'change password',
    'remember me',
    'trust this device',
    'learn more',
    'privacy',
    'terms',
    'contact',
    'support',
    'feedback',
    'report',
    'save',
    'copy',
    'download',
    'print',
    'edit',
    'delete',
    'remove',
    'clear',
    'refresh',
    'reload',
    'logout',
    'log out',
    'sign out',
    'exit',

    // Polish
    'szukaj',
    'wyszukaj',
    'zamknij',
    'anuluj',
    'wróć',
    'cofnij',
    'poprzedni',
    'dołącz',
    'zarejestruj',
    'zarejestruj się',
    'rejestracja',
    'utwórz konto',
    'resetuj',
    'wyślij ponownie',
    'wyślij kod ponownie',
    'spróbuj ponownie',
    'pomoc',
    'pomiń',
    'później',
    'przypomnij później',
    'nie teraz',
    'użyj innej metody',
    'spróbuj inaczej',
    'zmień metodę',
    'zapomniałem hasła',
    'resetuj hasło',
    'zmień hasło',
    'zapamiętaj mnie',
    'zaufaj temu urządzeniu',
    'dowiedz się więcej',
    'prywatność',
    'regulamin',
    'kontakt',
    'wsparcie',
    'zapisz',
    'kopiuj',
    'pobierz',
    'drukuj',
    'edytuj',
    'usuń',
    'wyczyść',
    'odśwież',
    'wyloguj',
    'wyloguj się',

    // German
    'suchen',
    'schließen',
    'abbrechen',
    'zurück',
    'vorherige',
    'beitreten',
    'registrieren',
    'anmelden',
    'konto erstellen',
    'zurücksetzen',
    'erneut senden',
    'code erneut senden',
    'nochmal versuchen',
    'hilfe',
    'überspringen',
    'später',
    'später erinnern',
    'nicht jetzt',
    'andere methode verwenden',
    'anderen weg versuchen',
    'methode ändern',
    'passwort vergessen',
    'passwort zurücksetzen',
    'passwort ändern',
    'angemeldet bleiben',
    'diesem gerät vertrauen',
    'mehr erfahren',
    'datenschutz',
    'agb',
    'kontakt',
    'unterstützung',
    'speichern',
    'kopieren',
    'herunterladen',
    'drucken',
    'bearbeiten',
    'löschen',
    'entfernen',
    'leeren',
    'aktualisieren',
    'abmelden',
    'ausloggen',

    // French
    'rechercher',
    'fermer',
    'annuler',
    'retour',
    'précédent',
    'rejoindre',
    's\'inscrire',
    'créer un compte',
    'réinitialiser',
    'renvoyer',
    'renvoyer le code',
    'réessayer',
    'aide',
    'ignorer',
    'passer',
    'plus tard',
    'rappeler plus tard',
    'pas maintenant',
    'utiliser une autre méthode',
    'essayer autrement',
    'changer de méthode',
    'mot de passe oublié',
    'réinitialiser le mot de passe',
    'changer le mot de passe',
    'se souvenir de moi',
    'faire confiance à cet appareil',
    'en savoir plus',
    'confidentialité',
    'conditions',
    'contact',
    'assistance',
    'enregistrer',
    'copier',
    'télécharger',
    'imprimer',
    'modifier',
    'supprimer',
    'effacer',
    'actualiser',
    'déconnexion',
    'se déconnecter',

    // Spanish
    'buscar',
    'cerrar',
    'cancelar',
    'volver',
    'atrás',
    'anterior',
    'unirse',
    'registrarse',
    'crear cuenta',
    'restablecer',
    'reenviar',
    'reenviar código',
    'intentar de nuevo',
    'ayuda',
    'omitir',
    'saltar',
    'más tarde',
    'recordar más tarde',
    'ahora no',
    'usar otro método',
    'probar de otra manera',
    'cambiar método',
    'olvidé mi contraseña',
    'restablecer contraseña',
    'cambiar contraseña',
    'recordarme',
    'confiar en este dispositivo',
    'más información',
    'privacidad',
    'términos',
    'contacto',
    'soporte',
    'guardar',
    'copiar',
    'descargar',
    'imprimir',
    'editar',
    'eliminar',
    'borrar',
    'actualizar',
    'cerrar sesión',
    'salir',

    // Portuguese
    'procurar',
    'pesquisar',
    'fechar',
    'cancelar',
    'voltar',
    'anterior',
    'juntar',
    'juntar-se',
    'registrar',
    'inscrever-se',
    'criar conta',
    'redefinir',
    'reenviar',
    'reenviar código',
    'tentar novamente',
    'ajuda',
    'pular',
    'depois',
    'mais tarde',
    'lembrar depois',
    'agora não',
    'usar outro método',
    'tentar de outra forma',
    'alterar método',
    'esqueci a senha',
    'redefinir senha',
    'alterar senha',
    'lembrar de mim',
    'confiar neste dispositivo',
    'saiba mais',
    'privacidade',
    'termos',
    'contato',
    'suporte',
    'salvar',
    'copiar',
    'baixar',
    'imprimir',
    'editar',
    'excluir',
    'remover',
    'limpar',
    'atualizar',
    'sair',
    'encerrar sessão',

    // Italian
    'cerca',
    'chiudi',
    'annulla',
    'indietro',
    'torna indietro',
    'precedente',
    'unisciti',
    'registrati',
    'iscriviti',
    'crea account',
    'reimposta',
    'reinvia',
    'reinvia codice',
    'riprova',
    'aiuto',
    'salta',
    'dopo',
    'più tardi',
    'ricordamelo dopo',
    'non ora',
    'usa un altro metodo',
    'prova in un altro modo',
    'cambia metodo',
    'password dimenticata',
    'reimposta password',
    'cambia password',
    'ricordami',
    'considera attendibile questo dispositivo',
    'scopri di più',
    'privacy',
    'termini',
    'contatto',
    'assistenza',
    'salva',
    'copia',
    'scarica',
    'stampa',
    'modifica',
    'elimina',
    'rimuovi',
    'cancella',
    'aggiorna',
    'esci',
    'disconnetti',

    // Dutch
    'zoeken',
    'sluiten',
    'annuleren',
    'terug',
    'vorige',
    'meedoen',
    'deelnemen',
    'registreren',
    'aanmelden',
    'account aanmaken',
    'resetten',
    'opnieuw verzenden',
    'code opnieuw verzenden',
    'opnieuw proberen',
    'hulp',
    'overslaan',
    'later',
    'herinner me later',
    'niet nu',
    'andere methode gebruiken',
    'probeer een andere manier',
    'methode wijzigen',
    'wachtwoord vergeten',
    'wachtwoord resetten',
    'wachtwoord wijzigen',
    'onthoud mij',
    'dit apparaat vertrouwen',
    'meer informatie',
    'privacy',
    'voorwaarden',
    'contact',
    'ondersteuning',
    'opslaan',
    'kopiëren',
    'downloaden',
    'afdrukken',
    'bewerken',
    'verwijderen',
    'wissen',
    'vernieuwen',
    'uitloggen',
    'afmelden',

    // Ukrainian
    'пошук',
    'шукати',
    'закрити',
    'скасувати',
    'відміна',
    'назад',
    'повернутися',
    'попередній',
    'приєднатися',
    'реєстрація',
    'зареєструватися',
    'створити обліковий запис',
    'скинути',
    'надіслати повторно',
    'надіслати код повторно',
    'спробувати знову',
    'допомога',
    'пропустити',
    'пізніше',
    'нагадати пізніше',
    'не зараз',
    'використати інший метод',
    'спробувати інакше',
    'змінити метод',
    'забули пароль',
    'скинути пароль',
    'змінити пароль',
    'запам\'ятати мене',
    'довіряти цьому пристрою',
    'дізнатися більше',
    'конфіденційність',
    'умови',
    'контакти',
    'підтримка',
    'зберегти',
    'копіювати',
    'завантажити',
    'друкувати',
    'редагувати',
    'видалити',
    'очистити',
    'оновити',
    'вийти',
    'вихід',

    // Turkish
    'ara',
    'aramak',
    'kapat',
    'iptal',
    'iptal et',
    'geri',
    'geri dön',
    'önceki',
    'katıl',
    'katılmak',
    'kayıt ol',
    'kayıt olmak',
    'üye ol',
    'hesap oluştur',
    'sıfırla',
    'tekrar gönder',
    'kodu tekrar gönder',
    'tekrar dene',
    'yardım',
    'atla',
    'daha sonra',
    'sonra hatırlat',
    'şimdi değil',
    'başka yöntem kullan',
    'başka bir yol dene',
    'yöntemi değiştir',
    'şifremi unuttum',
    'şifreyi sıfırla',
    'şifreyi değiştir',
    'beni hatırla',
    'bu cihaza güven',
    'daha fazla bilgi',
    'gizlilik',
    'şartlar',
    'iletişim',
    'destek',
    'kaydet',
    'kopyala',
    'indir',
    'yazdır',
    'düzenle',
    'sil',
    'kaldır',
    'temizle',
    'yenile',
    'çıkış',
    'çıkış yap',

    // Indonesian
    'cari',
    'pencarian',
    'tutup',
    'batal',
    'batalkan',
    'kembali',
    'sebelumnya',
    'bergabung',
    'daftar',
    'mendaftar',
    'buat akun',
    'atur ulang',
    'kirim ulang',
    'kirim ulang kode',
    'coba lagi',
    'bantuan',
    'lewati',
    'nanti',
    'ingatkan nanti',
    'tidak sekarang',
    'gunakan metode lain',
    'coba cara lain',
    'ubah metode',
    'lupa kata sandi',
    'atur ulang kata sandi',
    'ubah kata sandi',
    'ingat saya',
    'percayai perangkat ini',
    'pelajari lebih lanjut',
    'privasi',
    'ketentuan',
    'kontak',
    'dukungan',
    'simpan',
    'salin',
    'unduh',
    'cetak',
    'sunting',
    'hapus',
    'bersihkan',
    'muat ulang',
    'keluar',

    // Greek
    'αναζήτηση',
    'κλείσιμο',
    'κλείσε',
    'ακύρωση',
    'ακυρώνω',
    'πίσω',
    'προηγούμενο',
    'συμμετοχή',
    'εγγραφή',
    'δημιουργία λογαριασμού',
    'επαναφορά',
    'επανάληψη αποστολής',
    'επανάληψη αποστολής κωδικού',
    'δοκιμάστε ξανά',
    'βοήθεια',
    'παράλειψη',
    'αργότερα',
    'υπενθύμιση αργότερα',
    'όχι τώρα',
    'χρήση άλλης μεθόδου',
    'δοκιμάστε άλλο τρόπο',
    'αλλαγή μεθόδου',
    'ξεχάσατε τον κωδικό',
    'επαναφορά κωδικού',
    'αλλαγή κωδικού',
    'να με θυμάσαι',
    'εμπιστοσύνη σε αυτή τη συσκευή',
    'μάθετε περισσότερα',
    'απόρρητο',
    'όροι',
    'επικοινωνία',
    'υποστήριξη',
    'αποθήκευση',
    'αντιγραφή',
    'λήψη',
    'εκτύπωση',
    'επεξεργασία',
    'διαγραφή',
    'καθαρισμός',
    'ανανέωση',
    'αποσύνδεση',

    // Japanese
    '検索',
    '閉じる',
    'キャンセル',
    '戻る',
    '前へ',
    '参加',
    '登録',
    '新規登録',
    'アカウント作成',
    'リセット',
    '再送信',
    'コードを再送信',
    'もう一度試す',
    'ヘルプ',
    'スキップ',
    '後で',
    '後で通知',
    '今はしない',
    '別の方法を使用',
    '別の方法を試す',
    '方法を変更',
    'パスワードを忘れた',
    'パスワードをリセット',
    'パスワードを変更',
    'ログイン状態を保持',
    'このデバイスを信頼',
    '詳細',
    'プライバシー',
    '利用規約',
    'お問い合わせ',
    'サポート',
    '保存',
    'コピー',
    'ダウンロード',
    '印刷',
    '編集',
    '削除',
    'クリア',
    '更新',
    'ログアウト',
    'サインアウト',

    // Korean
    '검색',
    '닫기',
    '취소',
    '뒤로',
    '이전',
    '참여',
    '가입',
    '회원가입',
    '계정 만들기',
    '초기화',
    '재전송',
    '코드 재전송',
    '다시 시도',
    '도움말',
    '건너뛰기',
    '나중에',
    '나중에 알림',
    '지금은 안 함',
    '다른 방법 사용',
    '다른 방법 시도',
    '방법 변경',
    '비밀번호 찾기',
    '비밀번호 재설정',
    '비밀번호 변경',
    '로그인 유지',
    '이 기기 신뢰',
    '자세히 알아보기',
    '개인정보',
    '약관',
    '문의',
    '지원',
    '저장',
    '복사',
    '다운로드',
    '인쇄',
    '편집',
    '삭제',
    '지우기',
    '새로고침',
    '로그아웃',

    // Chinese (Simplified)
    '搜索',
    '关闭',
    '取消',
    '返回',
    '上一步',
    '加入',
    '注册',
    '创建账户',
    '重置',
    '重新发送',
    '重新发送代码',
    '重试',
    '帮助',
    '跳过',
    '稍后',
    '稍后提醒',
    '暂时不',
    '使用其他方式',
    '尝试其他方式',
    '更改方式',
    '忘记密码',
    '重置密码',
    '修改密码',
    '记住我',
    '信任此设备',
    '了解更多',
    '隐私',
    '条款',
    '联系',
    '支持',
    '保存',
    '复制',
    '下载',
    '打印',
    '编辑',
    '删除',
    '清除',
    '刷新',
    '退出',
    '登出',

    // Chinese (Traditional)
    '搜尋',
    '關閉',
    '取消',
    '返回',
    '上一步',
    '加入',
    '註冊',
    '建立帳戶',
    '重設',
    '重新傳送',
    '重新傳送代碼',
    '重試',
    '說明',
    '略過',
    '稍後',
    '稍後提醒',
    '暫時不要',
    '使用其他方式',
    '嘗試其他方式',
    '變更方式',
    '忘記密碼',
    '重設密碼',
    '變更密碼',
    '記住我',
    '信任此裝置',
    '瞭解更多',
    '隱私權',
    '條款',
    '聯絡',
    '支援',
    '儲存',
    '複製',
    '下載',
    '列印',
    '編輯',
    '刪除',
    '清除',
    '重新整理',
    '登出',

    // Arabic
    'بحث',
    'إغلاق',
    'إلغاء',
    'رجوع',
    'السابق',
    'انضمام',
    'تسجيل',
    'إنشاء حساب',
    'إعادة تعيين',
    'إعادة الإرسال',
    'إعادة إرسال الرمز',
    'حاول مرة أخرى',
    'مساعدة',
    'تخطي',
    'لاحقاً',
    'تذكيري لاحقاً',
    'ليس الآن',
    'استخدام طريقة أخرى',
    'جرب طريقة أخرى',
    'تغيير الطريقة',
    'نسيت كلمة المرور',
    'إعادة تعيين كلمة المرور',
    'تغيير كلمة المرور',
    'تذكرني',
    'الوثوق بهذا الجهاز',
    'معرفة المزيد',
    'الخصوصية',
    'الشروط',
    'اتصل بنا',
    'الدعم',
    'حفظ',
    'نسخ',
    'تحميل',
    'طباعة',
    'تعديل',
    'حذف',
    'مسح',
    'تحديث',
    'تسجيل الخروج',

    // Hebrew
    'חיפוש',
    'סגור',
    'ביטול',
    'חזרה',
    'הקודם',
    'הצטרף',
    'הרשמה',
    'יצירת חשבון',
    'איפוס',
    'שלח שוב',
    'שלח קוד שוב',
    'נסה שוב',
    'עזרה',
    'דלג',
    'מאוחר יותר',
    'הזכר לי מאוחר יותר',
    'לא עכשיו',
    'השתמש בשיטה אחרת',
    'נסה דרך אחרת',
    'שנה שיטה',
    'שכחתי סיסמה',
    'איפוס סיסמה',
    'שינוי סיסמה',
    'זכור אותי',
    'בטח במכשיר זה',
    'למידע נוסף',
    'פרטיות',
    'תנאים',
    'צור קשר',
    'תמיכה',
    'שמור',
    'העתק',
    'הורד',
    'הדפס',
    'ערוך',
    'מחק',
    'נקה',
    'רענן',
    'התנתק',

    // Hindi
    'खोज',
    'खोजें',
    'बंद करें',
    'रद्द करें',
    'वापस',
    'पिछला',
    'शामिल हों',
    'पंजीकरण',
    'साइन अप',
    'खाता बनाएं',
    'रीसेट',
    'पुनः भेजें',
    'कोड पुनः भेजें',
    'पुनः प्रयास करें',
    'सहायता',
    'छोड़ें',
    'बाद में',
    'बाद में याद दिलाएं',
    'अभी नहीं',
    'अन्य विधि का उपयोग करें',
    'दूसरा तरीका आज़माएं',
    'विधि बदलें',
    'पासवर्ड भूल गए',
    'पासवर्ड रीसेट करें',
    'पासवर्ड बदलें',
    'मुझे याद रखें',
    'इस डिवाइस पर भरोसा करें',
    'और जानें',
    'गोपनीयता',
    'शर्तें',
    'संपर्क',
    'सहायता',
    'सहेजें',
    'कॉपी',
    'डाउनलोड',
    'प्रिंट',
    'संपादित करें',
    'हटाएं',
    'साफ़ करें',
    'रीफ्रेश',
    'लॉग आउट',

    // Thai
    'ค้นหา',
    'ปิด',
    'ยกเลิก',
    'ย้อนกลับ',
    'ก่อนหน้า',
    'เข้าร่วม',
    'ลงทะเบียน',
    'สมัครสมาชิก',
    'สร้างบัญชี',
    'รีเซ็ต',
    'ส่งอีกครั้ง',
    'ส่งรหัสอีกครั้ง',
    'ลองอีกครั้ง',
    'ช่วยเหลือ',
    'ข้าม',
    'ภายหลัง',
    'เตือนภายหลัง',
    'ไม่ใช่ตอนนี้',
    'ใช้วิธีอื่น',
    'ลองวิธีอื่น',
    'เปลี่ยนวิธี',
    'ลืมรหัสผ่าน',
    'รีเซ็ตรหัสผ่าน',
    'เปลี่ยนรหัสผ่าน',
    'จดจำฉัน',
    'เชื่อถืออุปกรณ์นี้',
    'เรียนรู้เพิ่มเติม',
    'ความเป็นส่วนตัว',
    'ข้อกำหนด',
    'ติดต่อ',
    'สนับสนุน',
    'บันทึก',
    'คัดลอก',
    'ดาวน์โหลด',
    'พิมพ์',
    'แก้ไข',
    'ลบ',
    'ล้าง',
    'รีเฟรช',
    'ออกจากระบบ',

    // Vietnamese
    'tìm kiếm',
    'đóng',
    'hủy',
    'hủy bỏ',
    'quay lại',
    'trước',
    'tham gia',
    'đăng ký',
    'tạo tài khoản',
    'đặt lại',
    'gửi lại',
    'gửi lại mã',
    'thử lại',
    'trợ giúp',
    'bỏ qua',
    'sau',
    'nhắc tôi sau',
    'không phải bây giờ',
    'dùng phương thức khác',
    'thử cách khác',
    'đổi phương thức',
    'quên mật khẩu',
    'đặt lại mật khẩu',
    'đổi mật khẩu',
    'nhớ tôi',
    'tin tưởng thiết bị này',
    'tìm hiểu thêm',
    'quyền riêng tư',
    'điều khoản',
    'liên hệ',
    'hỗ trợ',
    'lưu',
    'sao chép',
    'tải xuống',
    'in',
    'chỉnh sửa',
    'xóa',
    'xóa sạch',
    'làm mới',
    'đăng xuất',

    // Czech
    'hledat',
    'vyhledat',
    'zavřít',
    'zrušit',
    'zpět',
    'předchozí',
    'připojit se',
    'registrovat',
    'registrace',
    'vytvořit účet',
    'resetovat',
    'odeslat znovu',
    'odeslat kód znovu',
    'zkusit znovu',
    'nápověda',
    'přeskočit',
    'později',
    'připomenout později',
    'teď ne',
    'použít jinou metodu',
    'zkusit jinak',
    'změnit metodu',
    'zapomenuté heslo',
    'resetovat heslo',
    'změnit heslo',
    'zapamatovat si mě',
    'důvěřovat tomuto zařízení',
    'zjistit více',
    'soukromí',
    'podmínky',
    'kontakt',
    'podpora',
    'uložit',
    'kopírovat',
    'stáhnout',
    'tisknout',
    'upravit',
    'smazat',
    'vymazat',
    'obnovit',
    'odhlásit se',

    // Swedish
    'sök',
    'sökа',
    'stäng',
    'avbryt',
    'tillbaka',
    'föregående',
    'gå med',
    'registrera',
    'skapa konto',
    'återställ',
    'skicka igen',
    'skicka kod igen',
    'försök igen',
    'hjälp',
    'hoppa över',
    'senare',
    'påminn mig senare',
    'inte nu',
    'använd annan metod',
    'prova ett annat sätt',
    'ändra metod',
    'glömt lösenord',
    'återställ lösenord',
    'ändra lösenord',
    'kom ihåg mig',
    'lita på denna enhet',
    'läs mer',
    'integritet',
    'villkor',
    'kontakt',
    'support',
    'spara',
    'kopiera',
    'ladda ner',
    'skriv ut',
    'redigera',
    'radera',
    'ta bort',
    'rensa',
    'uppdatera',
    'logga ut',

    // Norwegian
    'søk',
    'søke',
    'lukk',
    'avbryt',
    'tilbake',
    'forrige',
    'bli med',
    'registrer',
    'opprett konto',
    'tilbakestill',
    'send på nytt',
    'send kode på nytt',
    'prøv igjen',
    'hjelp',
    'hopp over',
    'senere',
    'påminn meg senere',
    'ikke nå',
    'bruk en annen metode',
    'prøv en annen måte',
    'endre metode',
    'glemt passord',
    'tilbakestill passord',
    'endre passord',
    'husk meg',
    'stol på denne enheten',
    'lær mer',
    'personvern',
    'vilkår',
    'kontakt',
    'støtte',
    'lagre',
    'kopier',
    'last ned',
    'skriv ut',
    'rediger',
    'slett',
    'fjern',
    'tøm',
    'oppdater',
    'logg ut',

    // Danish
    'søg',
    'søge',
    'luk',
    'annuller',
    'tilbage',
    'forrige',
    'deltag',
    'tilmeld',
    'opret konto',
    'nulstil',
    'send igen',
    'send kode igen',
    'prøv igen',
    'hjælp',
    'spring over',
    'senere',
    'påmind mig senere',
    'ikke nu',
    'brug en anden metode',
    'prøv en anden måde',
    'skift metode',
    'glemt adgangskode',
    'nulstil adgangskode',
    'skift adgangskode',
    'husk mig',
    'stol på denne enhed',
    'læs mere',
    'privatliv',
    'vilkår',
    'kontakt',
    'support',
    'gem',
    'kopier',
    'download',
    'udskriv',
    'rediger',
    'slet',
    'fjern',
    'ryd',
    'opdater',
    'log ud',

    // Finnish
    'hae',
    'etsi',
    'sulje',
    'peruuta',
    'takaisin',
    'edellinen',
    'liity',
    'rekisteröidy',
    'luo tili',
    'palauta',
    'lähetä uudelleen',
    'lähetä koodi uudelleen',
    'yritä uudelleen',
    'ohje',
    'ohita',
    'myöhemmin',
    'muistuta myöhemmin',
    'ei nyt',
    'käytä toista menetelmää',
    'kokeile toista tapaa',
    'vaihda menetelmää',
    'unohtunut salasana',
    'palauta salasana',
    'vaihda salasana',
    'muista minut',
    'luota tähän laitteeseen',
    'lue lisää',
    'tietosuoja',
    'ehdot',
    'yhteystiedot',
    'tuki',
    'tallenna',
    'kopioi',
    'lataa',
    'tulosta',
    'muokkaa',
    'poista',
    'tyhjennä',
    'päivitä',
    'kirjaudu ulos',

    // Hungarian
    'keresés',
    'keres',
    'bezárás',
    'bezár',
    'mégse',
    'vissza',
    'előző',
    'csatlakozás',
    'regisztráció',
    'regisztrál',
    'fiók létrehozása',
    'visszaállítás',
    'visszaállít',
    'újraküldés',
    'kód újraküldése',
    'próbálja újra',
    'súgó',
    'kihagyás',
    'később',
    'emlékeztessen később',
    'most nem',
    'másik módszer használata',
    'próbáljon más módot',
    'módszer módosítása',
    'elfelejtett jelszó',
    'jelszó visszaállítása',
    'jelszó módosítása',
    'emlékezzen rám',
    'eszköz megbízhatósága',
    'további információ',
    'adatvédelem',
    'feltételek',
    'kapcsolat',
    'támogatás',
    'mentés',
    'másolás',
    'letöltés',
    'nyomtatás',
    'szerkesztés',
    'törlés',
    'eltávolítás',
    'ürítés',
    'frissítés',
    'kijelentkezés',

    // Romanian
    'căutare',
    'caută',
    'închide',
    'anulează',
    'anulare',
    'înapoi',
    'anterior',
    'alătură-te',
    'înregistrare',
    'înregistrează-te',
    'creează cont',
    'resetare',
    'resetează',
    'retrimite',
    'retrimite codul',
    'încearcă din nou',
    'ajutor',
    'sari peste',
    'mai târziu',
    'amintește-mi mai târziu',
    'nu acum',
    'folosește altă metodă',
    'încearcă alt mod',
    'schimbă metoda',
    'am uitat parola',
    'resetare parolă',
    'schimbă parola',
    'ține-mă minte',
    'ai încredere în acest dispozitiv',
    'află mai multe',
    'confidențialitate',
    'termeni',
    'contact',
    'suport',
    'salvează',
    'copiază',
    'descarcă',
    'tipărește',
    'editează',
    'șterge',
    'elimină',
    'golește',
    'reîmprospătează',
    'deconectare',
    'ieșire'
  ];
};

export default ignoreButtonTexts;
