//
//  This file is part of the 2FAS Browser Extension (https://github.com/twofas/2fas-browser-extension)
//  Copyright © 2026 Two Factor Authentication Service, Inc.
//  Contributed by Grzegorz Zając. All rights reserved.
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program. If not, see <https://www.gnu.org/licenses/>
//

const config = {
  HTMLminify: {
    collapseBooleanAttributes: true,
    collapseInlineTagWhitespace: true,
    collapseWhitespace: true,
    includeAutoGeneratedTags: false,
    minifyCSS: true,
    minifyJS: true,
    minifyURLs: true,
    removeComments: true,
    removeEmptyAttributes: true,
    removeOptionalTags: true,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    removeTagWhitespace: true
  },

  SCSSLintConfigFile: './.stylelintrc',

  extPlatform: {
    chrome: {
      optionsPageTemplate: './src/optionsPage/optionsPage.html',
      filesList: {
        patterns: [
          {
            from: './src/manifest/chrome.json',
            to: '../manifest.json'
          },
          {
            context: './src/images/icons',
            from: '**/*',
            to: '../images/icons/'
          },
          {
            context: './src/fonts',
            from: '**/*',
            to: '../fonts/'
          }
        ]
      }
    },
    firefox: {
      optionsPageTemplate: './src/optionsPage/optionsPage.html',
      filesList: {
        patterns: [
          {
            from: './src/manifest/firefox.json',
            to: '../manifest.json'
          },
          {
            context: './src/images/icons',
            from: '**/*',
            to: '../images/icons/'
          },
          {
            context: './src/fonts',
            from: '**/*',
            to: '../fonts/'
          }
        ]
      }
    },
    opera: {
      optionsPageTemplate: './src/optionsPage/optionsPage.html',
      filesList: {
        patterns: [
          {
            from: './src/manifest/opera.json',
            to: '../manifest.json'
          },
          {
            context: './src/images/icons',
            from: '**/*',
            to: '../images/icons/'
          },
          {
            context: './src/fonts',
            from: '**/*',
            to: '../fonts/'
          }
        ]
      }
    },
    edge: {
      optionsPageTemplate: './src/optionsPage/optionsPage.html',
      filesList: {
        patterns: [
          {
            from: './src/manifest/edge.json',
            to: '../manifest.json'
          },
          {
            context: './src/images/icons',
            from: '**/*',
            to: '../images/icons/'
          },
          {
            context: './src/fonts',
            from: '**/*',
            to: '../fonts/'
          }
        ]
      }
    },
    safari: {
      optionsPageTemplate: './src/optionsPage/optionsPage.html',
      filesList: {
        patterns: [
          {
            from: './src/manifest/safari.json',
            to: '../manifest.json'
          },
          {
            context: './src/images/icons',
            from: '**/*',
            to: '../images/icons/'
          },
          {
            context: './src/fonts',
            from: '**/*',
            to: '../fonts/'
          }
        ]
      }
    }
  }
};

module.exports = config;
